import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import MenuIcon from '@mui/icons-material/Menu';
import Drawer from '@mui/material/Drawer';
import { useState } from 'react';

import InboxIcon from '@mui/icons-material/MoveToInbox';
import MailIcon from '@mui/icons-material/Mail';
import { Cancel } from '@mui/icons-material';
import { NavLink, Outlet, useLocation, useNavigate, useOutletContext } from 'react-router-dom';
import { Divider, List, ListItem, ListItemButton, ListItemIcon, ListItemText } from '@mui/material';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';


type RootContext = {
  onTitleChange: (t: string) => void;
}

export const useRootContext = () => useOutletContext<RootContext>();

export default function RootWindow() {
    const [drawerOpen, setDrawerOpen] = useState(false);
    const [title, setTitle] = useState("Home")
    const navigate = useNavigate();
    const location = useLocation();
    const doesAnyHistoryEntryExist = location.key !== "default";
    const drawerToggler = (open: boolean) =>
        (event: React.KeyboardEvent | React.MouseEvent) => {
        if (
          event.type === 'keydown' &&
          ((event as React.KeyboardEvent).key === 'Tab' ||
            (event as React.KeyboardEvent).key === 'Shift')
        ) {
          return;
        }
        setDrawerOpen(open);
    };

    const handleTitleChange = (title: string) => {
        setTitle(title);
    }

    const side_menus_section_1 = [{
        display_text: 'Home',
        navigate_path: '/',
        action : () => {
      }},
      {
      display_text: 'New Import',
      navigate_path: '/new_import',
      action : () => {
      }
    }]

    const side_menus_section_2 = [{
      display_text: 'Integrate with AI',
      navigate_path: '/coming_soon',
      action : () => {
      }
    }]

    const DrawerList = (
    <Box sx={{ width: 250 }} role="presentation" onClick={drawerToggler(false)}>
    <List>
      {side_menus_section_1.map((side_menu_item, index) => (
        <NavLink key={side_menu_item.display_text}
        style={{ textDecoration: 'none' }}
        to={side_menu_item.navigate_path}
      >
        {({ isActive, isPending, isTransitioning }) => (
        <ListItem key={side_menu_item.display_text} disablePadding>
            <ListItemButton onClick={side_menu_item.action} selected={isActive}>
              <ListItemIcon>
                {index % 2 === 0 ? <InboxIcon /> : <MailIcon />}
              </ListItemIcon>
              <ListItemText primary={side_menu_item.display_text} />
            </ListItemButton>
        </ListItem>
      )}
      </NavLink>
    ))}
    </List>
  <Divider />
  <List>
    {/* A helper towards all of your integrations and insights, autogenerated */}
    {side_menus_section_2.map((side_menu_item, index) => (
      <NavLink key={side_menu_item.display_text}
      to={side_menu_item.navigate_path}
      style={{ textDecoration: 'none' }}
    >
      {({ isActive, isPending, isTransitioning }) => (
      <ListItem key={side_menu_item.display_text} disablePadding>
        <ListItemButton onClick={side_menu_item.action} selected={isActive}>
          <ListItemIcon>
            {index % 2 === 0 ? <InboxIcon /> : <MailIcon />}
          </ListItemIcon>
          <ListItemText primary={side_menu_item.display_text} />
        </ListItemButton>
      </ListItem>
      )}
      </NavLink>
    ))}
  </List>
  </Box>
  );

    return (
    <Box sx={{ height: '100vh' }}>
      <Drawer
        anchor={'left'}
        open={drawerOpen}
        onClose={drawerToggler(false)}>
          <Toolbar />
            {DrawerList}
      </Drawer>
      <AppBar position="relative" sx={{ zIndex: (theme) => theme.zIndex.drawer + 1 }}>
        <Toolbar>
          { drawerOpen ? <IconButton
            size="small"
            edge="start"
            color="inherit"
            aria-label="menu"
            sx={{ mr: 2 }}
            onClick={drawerToggler(false)}
          >
             <Cancel />
          </IconButton> : <IconButton
            size="small"
            edge="start"
            color="inherit"
            aria-label="menu"
            sx={{ mr: 2 }}
            onClick={drawerToggler(true)}
          >
            <MenuIcon />
          </IconButton>
          }
          
          <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
            {title}
          </Typography>
          { doesAnyHistoryEntryExist && (<IconButton
            size="large"
            edge="start"
            color="inherit"
            aria-label="back"
            sx={{ mr: 2 }}
            onClick={() => navigate(-1)}
          >
            <ArrowBackIcon />
          </IconButton>)}
          
          
        </Toolbar>
      </AppBar>
      <Outlet context={{ onTitleChange: handleTitleChange } as RootContext}></Outlet>
    </Box>
    )
}