import List from '@mui/material/List';
import Divider from '@mui/material/Divider';
import ListItem from '@mui/material/ListItem';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemIcon from '@mui/material/ListItemIcon';
import ListItemText from '@mui/material/ListItemText';
import InboxIcon from '@mui/icons-material/MoveToInbox';
import MailIcon from '@mui/icons-material/Mail';
import { NavLink, Navigate, useNavigate } from 'react-router-dom';

export default function sideMenu() {

    const navigate =  useNavigate();

    const side_menus_section_1 = [{
      display_text: 'New Import',
      navigate_path: '/new_imports',
      action : () => {
      }
    }]

    const side_menus_section_2 = [{
      display_text: 'Integrate with AI',
      navigate_path: '/',
      action : () => {
        // callImportAPIs and cache it
      }
    }]

    // class styles = useStyles()

    return (<div><List>
    
    {side_menus_section_1.map((side_menu_item, index) => (
      <ListItem key={side_menu_item.display_text} disablePadding>
        <NavLink
          to={side_menu_item.navigate_path}
          className={({ isActive, isPending }) =>
            isPending ? "pending" : isActive ? "active" : ""
          }
        >
          <ListItemButton onClick={side_menu_item.action}>
            <ListItemIcon>
              {index % 2 === 0 ? <InboxIcon /> : <MailIcon />}
            </ListItemIcon>
            <ListItemText primary={side_menu_item.display_text} />
          </ListItemButton>
        </NavLink>
      </ListItem>
    ))}
  </List>
  <Divider />
  <List>
    {/* A helper towards all of your integrations and insights, autogenerated */}
    {side_menus_section_2.map((side_menu_item, index) => (
      <ListItem key={side_menu_item.display_text} disablePadding>
        <ListItemButton onClick={side_menu_item.action}>
          <ListItemIcon>
            {index % 2 === 0 ? <InboxIcon /> : <MailIcon />}
          </ListItemIcon>
          <ListItemText primary={side_menu_item.display_text} />
        </ListItemButton>
      </ListItem>
    ))}
  </List>
  </div>);
}